site_name: Dashboard Bauindustrie
site_description: Dokumentation für das Projektseminar
repo_url: https://github.com/just1130/dashboardDoc
theme: readthedocs
docs_dir: 'docs'
nav:
    - 'Introduction': 'index.md'
    - 'Handbuch' : 'handbuch.md'
    - 'Forecast_and_scraping' : 'forecast_and_scraping.md'
    - 'DynamicDashboard' : 'dynamicDashboard.md'
    - 'DashboardFrontend' : 'dashboardFrontend.md'

